/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 milk.gltf 
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export function Milk(props) {
  const { nodes, materials } = useGLTF('assets/models/milk/milk.gltf');

  const eventMilk = (e) => {
    props.handleMilk();
    e.stopPropagation();
  };

  return (
    <group {...props} dispose={null} onClick={(e) => eventMilk(e)}>
      <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
      <mesh
        geometry={nodes.Cube_2.geometry}
        material={materials['Material.001']}
      />
      <mesh
        geometry={nodes.Cube_3.geometry}
        material={materials['Material.002']}
      />
      <mesh
        geometry={nodes.Cube_4.geometry}
        material={materials['Material.003']}
      />
    </group>
  );
}

useGLTF.preload('assets/models/milk/milk.gltf');
