/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: Ju Designer (https://sketchfab.com/JuDesigner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/setup-gamer-1d994c5684224b8395e29cd9b3da1584
Title: Setup Gamer.
*/

import { Html, useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';
import { motion } from 'framer-motion-3d';
import React, { useRef, useState } from 'react';
import { toRadians } from '../../../../../../Config/Angles';

export function Setup(props) {
  const { nodes, materials } = useGLTF('assets/models/setup/scene.gltf');
  const screenGroupRef = useRef();
  const [isHovered, setIsHovered] = useState(false);

  const handleAnimate = () => {
    setIsHovered(true);
    setTimeout(() => {
      setIsHovered(false);
    }, 1000);
  };

  const handleRedirect = () => {
    window.open('https://jngds-1.josemanuelp2005.repl.co/', '_blank');
  };



  return (
    <group {...props} dispose={null}>
        <group
          position={[14.039, 0.745, -2.251]}
          rotation={[Math.PI, -1.563, Math.PI]}
          scale={[0.007, 0.001, 0.027]}
        >
          {/* Keyboard */}
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials['Material.005']}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials['Material.006']}
          />
        </group>
      <group
        position={[14.41, 0.734, -2.26]}
        rotation={[Math.PI, -1.563, Math.PI]}
        scale={[0.063, 0.063, 0.032]}
      >
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials['Material.009']}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials['Material.011']}
        />
      </group>
      <group
        position={[14.866, 0.826, -2.214]}
        rotation={[Math.PI, -1.561, 1.573]}
        scale={0.025}
      >
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials['Material.012']}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials['Material.013']}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials['Material.014']}
        />
      </group>
      <group
        position={[14.866, 0.947, -2.214]}
        rotation={[Math.PI, -1.561, 1.573]}
        scale={0.025}
      >
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials['Material.012']}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials['Material.013']}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials['Material.014']}
        />
      </group>
      <motion.group
        animate={{
          scale: isHovered ? 0.36 : 0.3,
        }}
        onClick={handleRedirect}
        ref={screenGroupRef}
        position={[14.038, 1.161, -2.493]}
        rotation={[Math.PI / 2, 0, 0.007]}
        // scale={[0.617, 0.87, 0.206]}
        onPointerMissed={(e) => handleAnimate()}
      >
        {/* Pantalla */}
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials['Material.015']}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials['Material.017']}
          rotation-y={toRadians(180)}
        />
      </motion.group>
      <group
        position={[14.866, 1.062, -2.213]}
        rotation={[Math.PI, -1.561, 1.573]}
        scale={0.025}
      >
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials['Material.012']}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials['Material.013']}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials['Material.014']}
        />
      </group>
      <group
        position={[14.202, 0.675, -2.458]}
        rotation={[3.135, 0.007, 3.141]}
        scale={[0.839, 1, 0.366]}
      >
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials['Material.018']}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials['Material.019']}
        />
      </group>
      <group
        position={[14.039, 0.744, -2.251]}
        rotation={[Math.PI, -1.563, Math.PI]}
        scale={[0.007, 0.001, 0.027]}
      >
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials['Material.005']}
        />
        <mesh
          geometry={nodes.Object_49.geometry}
          material={materials['Material.011']}
        />
      </group>
      <group
        position={[14.869, 0.947, -2.445]}
        rotation={[Math.PI, -1.561, Math.PI]}
        scale={[0.225, 0.201, 0.079]}
      >
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials['Material.020']}
        />
        <mesh
          geometry={nodes.Object_52.geometry}
          material={materials['Material.021']}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials['Material.004']}
        position={[14.868, 0.947, -2.411]}
        rotation={[Math.PI, -1.561, Math.PI]}
        scale={[0.195, 0.201, 0.079]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials['Material.010']}
        position={[14.703, 0.947, -2.447]}
        rotation={[Math.PI, -1.561, Math.PI]}
        scale={[0.24, 0.214, 0.085]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials['Material.015']}
        position={[14.017, 0.732, -2.548]}
        rotation={[Math.PI, -1.186, 1.564]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials['Material.015']}
        position={[14.079, 0.732, -2.575]}
        rotation={[0, 0, -1.577]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials['Material.009']}
        position={[14.42, 0.757, -2.316]}
        rotation={[0, -1.493, 1.916]}
        scale={[0.004, 0.005, 0.003]}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials['Material.015']}
        position={[14.04, 0.963, -2.578]}
        rotation={[-3.141, 0.007, 0]}
        scale={1.079}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.material_0}
        position={[13.461, 0.061, -2.764]}
        rotation={[Math.PI, -1.563, Math.PI]}
        scale={0.038}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.material_0}
        position={[14.953, 0.061, -2.753]}
        rotation={[Math.PI, -1.563, Math.PI]}
        scale={0.038}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.material_0}
        position={[14.949, 0.061, -2.163]}
        rotation={[Math.PI, -1.563, Math.PI]}
        scale={0.038}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.material_0}
        position={[13.453, 0.061, -2.174]}
        rotation={[Math.PI, -1.563, Math.PI]}
        scale={0.038}
      />
    </group>
  );
}

useGLTF.preload('assets/models/setup/scene.gltf');
